export const FETCH_MEASUREMENTS_SUCCESS = "FETCH_MEASUREMENTS_SUCCESS";
export const ADD_MEASUREMENT_INIT = "ADD_MEASUREMENT_INIT";
export const ADD_MEASUREMENT_SUCCESS = "ADD_MEASUREMENT_SUBMIT";

export const ADD_FOOD_INIT = "ADD_FOOD_INIT";
export const ADD_FOOD_SUCCESS = "ADD_FOOD_SUCCESS";
