export const BODY_MEASUREMENTS_INIT = "BODY_MEASUREMENTS_INIT";
export const BODY_MEASUREMENTS_SUCCESS = "BODY_MEASUREMENTS_SUBMIT";

export const ADD_FOOD_INIT = "ADD_FOOD_INIT";
export const ADD_FOOD_SUCCESS = "ADD_FOOD_SUCCESS";
