export const BODY_MEASUREMENT_INIT = "BODY_MEASUREMENT_INIT";
export const BODY_MEASUREMENT_SUCCESS = "BODY_MEASUREMENT_SUBMIT";

export const ADD_FOOD_INIT = "ADD_FOOD_INIT";
export const ADD_FOOD_SUCCESS = "ADD_FOOD_SUCCESS";
