export const FETCH_MEASUREMENTS_SUCCESS = "FETCH_MEASUREMENTS_SUCCESS";
export const ADD_MEASUREMENT_INIT = "ADD_MEASUREMENT_INIT";
export const ADD_MEASUREMENT_SUCCESS = "ADD_MEASUREMENT_SUBMIT";

export const FETCH_FOODS_SUCCESS = "FETCH_FOODS_SUCCESS";
export const ADD_FOOD_INIT = "ADD_FOOD_INIT";
export const ADD_FOOD_SUCCESS = "ADD_FOOD_SUCCESS";
export const REMOVE_FOOD_SUCCESS = "REMOVE_FOOD_SUCCESS";
